version: "3.8"
services:
  web:
    build: ./frontend
    image: frontend:v1
    ports:
      - 3000:3000
  api:
    build: ./backend
    image: backend:v1
    ports:
      - 5000:5000
    environment:
      DB_URL: mongodb://db/arminmernstack
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - arminmernstack:/data/db
volumes:
  arminmernstack:
